services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/qa-use
      - INNGEST_DEV=1
      - INNGEST_BASE_URL=http://inngest:8288
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    networks:
      - qause-network

  inngest:
    image: inngest/inngest
    command: 'inngest dev -u http://app:3000/api/inngest'
    depends_on:
      - app
    networks:
      - qause-network

  postgres:
    restart: always
    image: postgres:15
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=qa-use
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    command: postgres -c max_connections=1000
    networks:
      - qause-network

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    command: pnpm drizzle-kit migrate --config ./drizzle.config.ts
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/qa-use
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
    networks:
      - qause-network

networks:
  qause-network:
    driver: bridge
